/* Generated By:JavaCC: Do not edit this line. MtasCQLParserConstants.java */
package mtas.parser.cql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MtasCQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONTAINING = 5;
  /** RegularExpression Id. */
  int NOT_CONTAINING = 6;
  /** RegularExpression Id. */
  int WITHIN = 7;
  /** RegularExpression Id. */
  int NOT_WITHIN = 8;
  /** RegularExpression Id. */
  int INTERSECTING = 9;
  /** RegularExpression Id. */
  int NOT_INTERSECTING = 10;
  /** RegularExpression Id. */
  int FULLYALIGNEDWITH = 11;
  /** RegularExpression Id. */
  int NOT_FULLYALIGNEDWITH = 12;
  /** RegularExpression Id. */
  int GROUP_START = 13;
  /** RegularExpression Id. */
  int GROUP_END = 14;
  /** RegularExpression Id. */
  int WORD_START = 15;
  /** RegularExpression Id. */
  int WORD_END = 16;
  /** RegularExpression Id. */
  int BRACKET_START = 17;
  /** RegularExpression Id. */
  int BRACKET_END = 18;
  /** RegularExpression Id. */
  int CURLY_BRACKET_START = 19;
  /** RegularExpression Id. */
  int CURLY_BRACKET_END = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int QUESTION_MARK = 22;
  /** RegularExpression Id. */
  int NEGATION = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int KOMMA = 26;
  /** RegularExpression Id. */
  int TOKEN_NOTEQUALS = 27;
  /** RegularExpression Id. */
  int TOKEN_EQUALS = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int VARIABLE = 30;
  /** RegularExpression Id. */
  int QUOTED_VALUE = 31;
  /** RegularExpression Id. */
  int UNQUOTED_VALUE = 32;
  /** RegularExpression Id. */
  int OCTOTHORPE = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int ALLOWED_UNQUOTED_CHARACTER = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"containing\"",
    "\"!containing\"",
    "\"within\"",
    "\"!within\"",
    "\"intersecting\"",
    "\"!intersecting\"",
    "\"fullyalignedwith\"",
    "\"!fullyalignedwith\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"/\"",
    "\"?\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\",\"",
    "\"!=\"",
    "\"=\"",
    "<NUMBER>",
    "<VARIABLE>",
    "<QUOTED_VALUE>",
    "<UNQUOTED_VALUE>",
    "<OCTOTHORPE>",
    "<DIGIT>",
    "<ALLOWED_UNQUOTED_CHARACTER>",
  };

}
