/* Generated By:JavaCC: Do not edit this line. MtasFunctionParserConstants.java */
package mtas.parser.function;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MtasFunctionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 5;
  /** RegularExpression Id. */
  int LONG = 6;
  /** RegularExpression Id. */
  int DOUBLE = 7;
  /** RegularExpression Id. */
  int N = 8;
  /** RegularExpression Id. */
  int BASIC_OPERATOR_ADD = 9;
  /** RegularExpression Id. */
  int BASIC_OPERATOR_SUBTRACT = 10;
  /** RegularExpression Id. */
  int BASIC_OPERATOR_MULTIPLY = 11;
  /** RegularExpression Id. */
  int BASIC_OPERATOR_DIVIDE = 12;
  /** RegularExpression Id. */
  int BASIC_OPERATOR_POWER = 13;
  /** RegularExpression Id. */
  int BRACKET_START = 14;
  /** RegularExpression Id. */
  int BRACKET_END = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<VARIABLE>",
    "<LONG>",
    "<DOUBLE>",
    "\"$n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
  };

}
